version: 2.0
environment:
    CC_TEST_REPORTER_ID: 63dc0b387c0eea5ddb2549abb813f978783da00495992d3a8ecaff7f69fdfa6a
dependencies:
  post:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
test:
  pre:
    - ./cc-test-reporter before-build
  post:
    - ./cc-test-reporter after-build --exit-code $EXIT_CODE
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Get dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "test-results.xml"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml